### ISSUE TITLE
Undefined property: ReverseOAuth2\Authentication\Adapter\ReverseOAuth2::$events 

### ISSUE THREAD

**Issue by machek** [silvester/ReverseOAuth2#1]
I am getting 
Notice: Undefined property: ReverseOAuth2\Authentication\Adapter\ReverseOAuth2::$events in C:\projects\Matchbox5\module\ReverseOAuth2\src\ReverseOAuth2\Authentication\Adapter\ReverseOAuth2.php on line 60

looks property is missing

ReverseOAuth2\Authentication\Adapter\ReverseOAuth2::events

using ZF 2.0.3

**Comment by silvester** [comment]
Fixed it, I had another idea of using the shared event manager but canceled it. So i had the variable name for the event manager wrong. Pushed the new file to github.

Lp. Silvester
