### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by diemuzi** [silvester/ReverseOAuth2#12]
I was curious if you could update your documentation so that it is a little more clear on how to use this module. Installation seemed straight forward, but when it came time to use the module I've found myself to be quite lost.

For example. I create a test module just to experiment with this module. In order to access the URL I have to supply a route to the Controller / Action. I cannot find anywhere how to set the proper route for this module. Is it Literal or Segment or something else? If it's Segment or other, what does the actual route look like?

**Comment by silvester** [comment]
The first thing, the module does not provide any kind of action or controller. You are supposed to do it yourself. In the documentation part you can see the header "In your controller/action do:", this is a generic controller action and can be used in any url you need.

The library was supposed to be done decoupled from the controller. So the route is any url which uses at least the code written in the documentation.

The callback url needed for ouath2 is also your job, the url can be set in the config.

**Comment by diemuzi** [comment]
Guess it's not clicking for me. No worries, I'll keep searching for something else. Thanks anyways.
