### ISSUE TITLE
composer package

### ISSUE THREAD

**Issue by machek** [silvester/ReverseOAuth2#3]
Hi,
I think would be good to make module available as composer package, it's just a bit easier to add it into application this way.

https://packagist.org/

**Comment by silvester** [comment]
As far as i know the module is compliant with psr-0, so it just needs a composer.json file. I will look into it.

**Comment by machek** [comment]
Ok, thanks. It should be quite straight forward process and really helps when adding this module to an application.

**Comment by silvester** [comment]
Added package silvester/reverse-oauth2 to packagist.

Lp. Silvester

**Comment by machek** [comment]
I am having some problems when calling to "composer.phar updare", just wondering if require shouldn't be

 "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "2.*"
    }

Response which I am getting:

```
- Installation request for silvester/reverse-oauth2 dev-master -> satisfiable by silvester/reverse-oauth2
```

dev-master.
    - Conclusion: don't install zendframework/zendframework 2.0.0-beta4
    - Conclusion: don't install zendframework/zendframework 2.0.0beta4
    - silvester/reverse-oauth2 dev-master requires zendframework/zendframework dev-master -> satisfiable by zendframework/zendframework dev-master, libra/zendframework dev-default, zendframework/zendframework dev-master.

```
- Can only install one of: libra/zendframework dev-default, libra/zendframework 2.0.0.
- don't install libra/zendframework 2.0.0|don't install zendframework/zendframework dev-master
- don't install zendframework/zendframework dev-master|don't install libra/zendframework 2.0.0 .....
```

**Comment by machek** [comment]
Working well now. Thanks
