### ISSUE TITLE
Setting options programatically

### ISSUE THREAD

**Issue by chrisgahlert** [silvester/ReverseOAuth2#7]
Hi Silvester,

nice work so far. Seems pretty good and easy. I just have one little request:

Could you please add the methods `getOptions` and `setOption($name, $value)` to the class `AbstractOAuth2Client`? The reson for that is that it would be desirable to set e.g. the `redirect_uri` from within an action?

Thank you very much,
Chris

**Comment by silvester** [comment]
Makes sense. I will look into it tomorrow.

Lp. Silvester

**Comment by chrisgahlert** [comment]
Thanks! :+1:

**Comment by silvester** [comment]
Added client options object and some documentation. thanks for the idea.

Lp. Silvester
